import { createGoogleGenerativeAI } from '@ai-sdk/google';

const google = createGoogleGenerativeAI({
  apiKey: process.env.GeminiAPIKey,
});

export async function POST(req) {
  try {
    const { prompt, cardContent } = await req.json();

    if (!prompt && !cardContent) {
      return new Response(
        JSON.stringify({ error: '請提供圖片描述或文章內容' }),
        { status: 400, headers: { 'Content-Type': 'application/json' } }
      );
    }

    const imagePrompt = prompt || `Create an illustration that visually explains: ${cardContent.slice(0, 500)}`;

    // 使用 Google GenAI SDK 直接呼叫 Gemini 圖像生成
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp-image-generation:generateContent?key=${process.env.GeminiAPIKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: imagePrompt }]
          }],
          generationConfig: {
            responseModalities: ['TEXT', 'IMAGE'],
          }
        }),
      }
    );

    if (!response.ok) {
      const errorData = await response.json();
      console.error('Gemini API Error:', errorData);
      throw new Error(errorData.error?.message || 'Image generation failed');
    }

    const data = await response.json();
    
    // 從回應中提取圖片
    let imageUrl = null;
    let responseText = null;
    
    if (data.candidates && data.candidates[0]?.content?.parts) {
      for (const part of data.candidates[0].content.parts) {
        if (part.inlineData) {
          // 圖片是 base64 編碼的
          const base64Image = part.inlineData.data;
          const mimeType = part.inlineData.mimeType || 'image/png';
          imageUrl = `data:${mimeType};base64,${base64Image}`;
        } else if (part.text) {
          responseText = part.text;
        }
      }
    }

    if (!imageUrl) {
      throw new Error('No image was generated');
    }

    return new Response(
      JSON.stringify({ 
        success: true,
        imageUrl: imageUrl,
        enhancedPrompt: imagePrompt,
        responseText: responseText,
        note: 'Generated by Gemini 2.0 Flash Image (Nano Banana)'
      }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Generate Image API Error:', error);
    return new Response(
      JSON.stringify({ error: error.message || '圖片生成失敗' }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }
}
